### ISSUE TITLE
GithubNotifications Error

### ISSUE THREAD

**Issue by kraanzu** [elParaguayo/qtile-extras#385]
Hi, I'm trying to use the `GithubNoticiations` widget but it crashes with the following error:

> [!NOTE]
> Qtle Version: `0.29.0`
> Qtile Extras Version: `0.28.1`

```
2024-10-30 10:17:46,329 ERROR libqtile bar.py:_configure_widget():L390 GithubNotifications widget crashed during _configure with error:
Traceback (most recent call last):
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 190, in default_size
    return self._default_size
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ImgMask' object has no attribute '_default_size'. Did you mean: 'default_size'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 181, in default_surface
    return self._default_surface
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ImgMask' object has no attribute '_default_surface'. Did you mean: 'default_surface'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/bar.py", line 381, in _configure_widget
    widget._configure(self.qtile, self)
  File "/nix/store/hvsxg3wrbkxpk5glk8ypz64gkf8gk6nk-python3.12-qtile-extras-0.29.0/lib/python3.12/site-packages/qtile_extras/widget/decorations.py", line 966, in new_configure
    self.old_configure(qtile, bar)
  File "/nix/store/hvsxg3wrbkxpk5glk8ypz64gkf8gk6nk-python3.12-qtile-extras-0.29.0/lib/python3.12/site-packages/qtile_extras/widget/githubnotifications.py", line 88, in _configure
    self._load_icon()
  File "/nix/store/hvsxg3wrbkxpk5glk8ypz64gkf8gk6nk-python3.12-qtile-extras-0.29.0/lib/python3.12/site-packages/qtile_extras/widget/githubnotifications.py", line 110, in _load_icon
    self.img.resize(size)
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 202, in resize
    width0, height0 = self.default_size
                      ^^^^^^^^^^^^^^^^^
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 192, in default_size
    surf = self.default_surface
           ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 183, in default_surface
    surf, fmt = get_cairo_surface(self.bytes_img)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 39, in get_cairo_surface
    surf, fmt = cairocffi.pixbuf.decode_to_image_surface(bytes_img, width, height)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fn11byrl8zjf7kmm08kahy3xiqlx756a-python3.12-cairocffi-1.7.1/lib/python3.12/site-packages/cairocffi/pixbuf.py", line 129, in decode_to_image_surface
    pixbuf, format_name = decode_to_pixbuf(image_data, width, height)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fn11byrl8zjf7kmm08kahy3xiqlx756a-python3.12-cairocffi-1.7.1/lib/python3.12/site-packages/cairocffi/pixbuf.py", line 100, in decode_to_pixbuf
    handle_g_error(error, gdk_pixbuf.gdk_pixbuf_loader_close(loader, error))
  File "/nix/store/fn11byrl8zjf7kmm08kahy3xiqlx756a-python3.12-cairocffi-1.7.1/lib/python3.12/site-packages/cairocffi/pixbuf.py", line 64, in handle_g_error
    raise ImageLoadingError(message)
cairocffi.pixbuf.ImageLoadingError: Pixbuf error: Unrecognized image file format
2024-10-30 10:17:55,915 WARNING libqtile core.py:graceful_shutdown():L902 Server disconnected, couldn't close windows gracefully.
2024-10-30 10:17:55,915 WARNING libqtile core.py:_xpoll():L355 Shutting down due to disconnection from X server
2024-10-30 10:17:55,915 WARNING libqtile core.py:graceful_shutdown():L902 Server disconnected, couldn't close windows gracefully.
2024-10-30 10:17:55,916 WARNING libqtile core.py:graceful_shutdown():L902 Server disconnected, couldn't close windows gracefully.
2024-10-30 10:17:55,918 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2024-10-30 10:18:24,947 ERROR libqtile bar.py:_configure_widget():L390 GithubNotifications widget crashed during _configure with error:
Traceback (most recent call last):
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 190, in default_size
    return self._default_size
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ImgMask' object has no attribute '_default_size'. Did you mean: 'default_size'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 181, in default_surface
    return self._default_surface
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ImgMask' object has no attribute '_default_surface'. Did you mean: 'default_surface'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/bar.py", line 381, in _configure_widget
    widget._configure(self.qtile, self)
  File "/nix/store/hvsxg3wrbkxpk5glk8ypz64gkf8gk6nk-python3.12-qtile-extras-0.29.0/lib/python3.12/site-packages/qtile_extras/widget/decorations.py", line 966, in new_configure
    self.old_configure(qtile, bar)
  File "/nix/store/hvsxg3wrbkxpk5glk8ypz64gkf8gk6nk-python3.12-qtile-extras-0.29.0/lib/python3.12/site-packages/qtile_extras/widget/githubnotifications.py", line 88, in _configure
    self._load_icon()
  File "/nix/store/hvsxg3wrbkxpk5glk8ypz64gkf8gk6nk-python3.12-qtile-extras-0.29.0/lib/python3.12/site-packages/qtile_extras/widget/githubnotifications.py", line 110, in _load_icon
    self.img.resize(size)
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 202, in resize
    width0, height0 = self.default_size
                      ^^^^^^^^^^^^^^^^^
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 192, in default_size
    surf = self.default_surface
           ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 183, in default_surface
    surf, fmt = get_cairo_surface(self.bytes_img)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/safm92fcq50k7x459ryl34p2b6620w5b-python3.12-qtile-0.29.0/lib/python3.12/site-packages/libqtile/images.py", line 39, in get_cairo_surface
    surf, fmt = cairocffi.pixbuf.decode_to_image_surface(bytes_img, width, height)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fn11byrl8zjf7kmm08kahy3xiqlx756a-python3.12-cairocffi-1.7.1/lib/python3.12/site-packages/cairocffi/pixbuf.py", line 129, in decode_to_image_surface
    pixbuf, format_name = decode_to_pixbuf(image_data, width, height)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fn11byrl8zjf7kmm08kahy3xiqlx756a-python3.12-cairocffi-1.7.1/lib/python3.12/site-packages/cairocffi/pixbuf.py", line 100, in decode_to_pixbuf
    handle_g_error(error, gdk_pixbuf.gdk_pixbuf_loader_close(loader, error))
  File "/nix/store/fn11byrl8zjf7kmm08kahy3xiqlx756a-python3.12-cairocffi-1.7.1/lib/python3.12/site-packages/cairocffi/pixbuf.py", line 64, in handle_g_error
    raise ImageLoadingError(message)
cairocffi.pixbuf.ImageLoadingError: Pixbuf error: Unrecognized image file format
```

**Comment by elParaguayo** [comment]
Very strange. This error should have been fixed in qtile 0.29.0. The widget is also working for me.

Will take a look when I can

**Comment by elParaguayo** [comment]
Just tested on qtile 0.29 and qtile-extras 0.29 (although nothing has changed since 0.28.1 in qtile-extras for this widget) and it works fine for me.

Has the widget worked for you before or is this the first time you've used it? You need `librsvg` installed to have support for svg images in qtile.

**Comment by kraanzu** [comment]
> is this the first time you've used it?

First time

> You need librsvg installed to have support for svg images in qtile.

Hmm...lemme try with that. Thanks!

**Comment by kraanzu** [comment]
Update: Nope. It's still the same error even after adding `librsvg`

**Comment by elParaguayo** [comment]
Can you try the code in [this post](https://stackoverflow.com/a/40740651) and paste the answer here.

**Comment by kraanzu** [comment]
Hi again, Yes. I get this:

```python
['png', 'jpeg', 'bmp', 'gif', 'icns', 'ico', 'pnm', 'qtif', 'tga', 'tiff', 'xbm', 'xpm']
```

But something to note here: it ran when I used python3.11 but failed with circular import on python3.12. Although I am not sure if it has anything to do with the error

**Comment by elParaguayo** [comment]
So there's no svg support listed there. Did you restart qtile (exit and restart, as opposed to reloading config) after installing `librsvg`?

**Comment by kraanzu** [comment]
Yes. I even did a reboot

**Comment by elParaguayo** [comment]
Can you try running `gdk-pixbuf-query-loaders --update-cache` and restarting?

**Comment by kraanzu** [comment]
Ok so this worked for me:

```nix
services.xserver.gdk-pixbuf.modulePackages = [ pkgs.librsvg ];
```

So the issue was the missing library after all. Thank you and Happy Halloween! :)

**Comment by elParaguayo** [comment]
Great. Well done for working it out.
