### ISSUE TITLE
 [Wayland] Contex menus don't work anymore in statusnotifier widget

### ISSUE THREAD

**Issue by cr1ogen** [elParaguayo/qtile-extras#45]
As the title says, the context menu of the StatusNotifier widget no longer works.Before it worked in wayland (in X11 it still works)

**Comment by elParaguayo** [comment]
Interesting. 

I don't use Wayland so hadn't seen this but I suspect it's due to the changes that were made recently to how we handle certain window types.

I susoect any fix would be at the qtile level, rather than in this repo.

**Comment by elParaguayo** [comment]
Hmm. Having tested it. Context menu works for me  Tested with both vlc and remmina.

**Comment by cr1ogen** [comment]
Okay.  I tried with Steam and OBS, later when I get home from work I'll try with your 2 applications.  Maybe it stopped working with apps that use Xwayland

**Comment by cr1ogen** [comment]
vlc and remmina doesn't even show the icons in my StatusNotifier config, neither Wayland nor X11.
Now in obs it does show the context menu, but in steam it doesn't and when I click on the icon it shows me this message

`2022-03-04 23:18:42,162 ERROR libqtile loop.py:_handle_exception():L63 division by zero
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/qtile_extras-0.1.0-py3.9.egg/qtile_extras/widget/statusnotifier.py", line 231, in parse_menu
    callback(menu)
  File "/usr/local/lib/python3.9/dist-packages/qtile_extras-0.1.0-py3.9.egg/qtile_extras/widget/statusnotifier.py", line 373, in display_menu
    self.menu = PopupMenu.from_dbus_menu(self.qtile, menu_items, **self.menu_config)
  File "/usr/local/lib/python3.9/dist-packages/qtile_extras-0.1.0-py3.9.egg/qtile_extras/popup/menu.py", line 188, in from_dbus_menu
    return cls.generate(qtile, menuitems, **config)
  File "/usr/local/lib/python3.9/dist-packages/qtile_extras-0.1.0-py3.9.egg/qtile_extras/popup/menu.py", line 212, in generate
    return cls(qtile, controls=menuitems, **menu_config)
  File "/usr/local/lib/python3.9/dist-packages/qtile_extras-0.1.0-py3.9.egg/qtile_extras/popup/menu.py", line 146, in __init__
    PopupGridLayout.__init__(self, qtile, controls=controls, **config)
  File "/usr/local/lib/python3.9/dist-packages/qtile_extras-0.1.0-py3.9.egg/qtile_extras/popup/toolkit.py", line 398, in __init__
    self._width = self.rows * round((self.width - 2 * self.margin) / self.rows)
ZeroDivisionError: division by zero`

**Comment by cr1ogen** [comment]
And this is a general log, from my Qtile

`2022-03-04 23:06:23,113 ERROR libqtile loop.py:_handle_exception():L63 invalid object path: org.kde.StatusNotifierItem-2880-2
Trace (most recent recent calls):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/libqtile/widget/statusnotifier.py", line 480, in item_added
    success = future.result()
  File "/usr/local/lib/python3.9/dist-packages/libqtile/widget/statusnotifier.py", line 97, at start
    introspect = expect self.bus.introspect(self.service, self.path)
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/aio/message_bus.py", line 214, in introspection
    super().introspect(bus_name, route, answer_handler)
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/message_bus.py", line 204, in introspection
    Message(destination=bus_name,
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/message.py", line 92, in __init__
    assert_object_path_valid(auto.path)
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/validators.py", line 153, in assert_object_path_valid
    raise InvalidObjectPathError(path)
dbus_next.errors.InvalidObjectPathError: invalid object path: org.kde.StatusNotifierItem-2880-2
2022-03-04 23:07:37,909 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-03-04 23:07:48,850 WARNING libqtile prompt.py:_configure():L429 Prompt widget only supports audible chime on X11
2022-03-04 23:07:48,850 WARNING libqtile tasklist.py:_configure():L294 Tasklist icons are not supported in Wayland.
2022-03-04 23:09:47,211 WARNING libqtile prompt.py:_configure():L429 Prompt widget only supports audible chime on X11
2022-03-04 23:09:47,211 WARNING libqtile tasklist.py:_configure():L294 Tasklist icons are not supported in Wayland.
2022-03-04 23:12:42,298 WARNING libqtile prompt.py:_configure():L429 Prompt widget only supports audible chime on X11
2022-03-04 23:12:42,299 WARNING libqtile tasklist.py:_configure():L294 Tasklist icons are not supported in Wayland.`

**Comment by elParaguayo** [comment]
Thanks for posting more info.

I tried installing obs and steam and the menus work on both of them for me.

Your first error is interesting as it suggests that there are no menu items. I don't think the code currently handles that possibility so I can try adding something there. However, as above, the menus work for me so I'm not sure this is the problem.

**Comment by elParaguayo** [comment]
I've pushed a change that will stop the widget trying to create a menu when there are no menu items. You could see if that makes any difference here.

**Comment by cr1ogen** [comment]
> I've pushed a change that will stop the widget trying to create a menu when there are no menu items. You could see if that makes any difference here.

Update the repository and do not notice any changes. Also as you say, maybe it's more because of the qtile code, since I'm always updating it and it worked before.
Also do not worry about this issue, but it would be nice if they could incorporate part of the code of your StatusNotifier widget to the official Qtile since yours has context menus, in order to improve it

**Comment by elParaguayo** [comment]
It will never be merged into the main repo as there's too much extra code required.

If the menus worked before, can you try doing a `git bisect`? Again, I'm dubious if that would work because I can't replicate this

**Comment by cr1ogen** [comment]
I update all pip packages and steam context menu and obs started working. But I have to restart qtile with mod+ctrl+r for it to work. I guess it's some problem with the qtile bar, because sometimes when I move the mouse up in some widget the pointer disappears. Also for the mouse pointer to appear I have to have a window open, but that is already a problem of qtile with wayland. So I'm going to close this issue. Thank you very much

**Comment by cr1ogen** [comment]
I install nm-tray (QT app) and give me this error in the log file

`Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/libqtile/widget/statusnotifier.py", line 480, in item_added
    success = future.result()
  File "/usr/local/lib/python3.9/dist-packages/libqtile/widget/statusnotifier.py", line 97, in start
    introspection = await self.bus.introspect(self.service, self.path)
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/aio/message_bus.py", line 214, in introspect
    super().introspect(bus_name, path, reply_handler)
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/message_bus.py", line 204, in introspect
    Message(destination=bus_name,
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/message.py", line 92, in __init__
    assert_object_path_valid(self.path)
  File "/usr/local/lib/python3.9/dist-packages/dbus_next/validators.py", line 153, in assert_object_path_valid
    raise InvalidObjectPathError(path)
dbus_next.errors.InvalidObjectPathError: invalid object path: org.kde.StatusNotifierItem-1771-1`

An this in the app (i launched by kitty)

`QSystemTrayIcon::setVisible: No Icon set
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.NoReply", "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")`

I re-open the issue. If you want, feel free to close it. Thank you

**Comment by elParaguayo** [comment]
The second error message is hopefully fixed by https://github.com/qtile/qtile/pull/3434

I've installed `nm-tray` from the AUR but can't get it to run. Get an error `No Icon Set`. This happens because they don't provide any fallback icons. There's an unmerged PR that fixes this so I may have to build it manually unless you know how to fix that (the fix in https://github.com/palinek/nm-tray/issues/40 didn't work for me).

**Comment by elParaguayo** [comment]
OK. Built from git with their PR to add fallback icons.

Menus work for me on both.

**Comment by cr1ogen** [comment]
Yes, I am using the latest version.  When I get off work I'll update qtile with the latest changes

**Comment by cr1ogen** [comment]
I have applied the changes in Qtile, in my case nm-tray still does not show the icon in the system tray, but icons that were not shown before like VLC now do.
The context menus for which I made this issue now work, but first I have to restart qtile with mod4+Ctrl+R for them to do so.

**Comment by elParaguayo** [comment]
You really shouldn't have to restart. Do any of your widgets respond to mouse clicks before restarting?

**Comment by cr1ogen** [comment]
> 

No, the mouse does not respond to clicks before restart

**Comment by elParaguayo** [comment]
Can you check if the same thing happens if you remove the status notifier widget. If it does, post an issue on the qtile repo instead and we'll take a look.
